import { useState } from 'react';

const PrivacyAndTerms = () => {
  const [showAdvanced, setShowAdvanced] = useState(false);

  const toggleAdvanced = () => {
    setShowAdvanced(!showAdvanced);
  };

  return (
    <div className="privacy-terms">
      <h1>Prince AI - Privacy Policy and Terms of Service</h1>
      <p>Last updated: October 27, 2023</p>

      <h2>Privacy Policy</h2>
      {/* ... (Privacy Policy content as before) ... */}

      <h2>Terms of Service</h2>
      <p>
        These Terms of Service govern your use of the Prince AI company assistant. By using our services, you agree to be bound by these terms.
      </p>
      <ul>
        <li>
          <b>Acceptable Use:</b> You agree to use the AI assistant for lawful purposes and in accordance with all applicable laws.  You may not use the AI assistant to create or distribute illegal content.
        </li>
        <li>
          <b>Account Responsibility:</b> You are responsible for maintaining the confidentiality of your account credentials and are liable for all activities under your account.
        </li>
        <li>
          <b>Intellectual Property:</b>  All content generated by our AI assistant, and the underlying AI technology itself, remains the property of Prince AI. You do not acquire ownership rights to this content.
        </li>
        <li>
          <b>Liability Limitations:</b> Prince AI is not liable for any damages, direct or indirect, arising from your use of the assistant.
        </li>
        <li>
            <b>Changes to Terms:</b> We reserve the right to update these Terms of Service at any time.  You will be notified of any material changes via a prominent notice on our website.
        </li>
         <li>
          <b>Disputes:</b> Any dispute arising from these Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction].
        </li>
      </ul>

     <h2>Contact Us</h2>
      <p>
        If you have any questions or concerns about these policies, please contact us at support@princeai.com.
      </p>

      {/* Advanced Options (expandable section for Terms, could be moved to Privacy) */}
      <button onClick={toggleAdvanced}>
        {showAdvanced ? "Hide Advanced Details" : "Show Advanced Details"}
      </button>
      {showAdvanced && (
        <div>
          {/* Add more detailed information about terms, possibly an agreement to arbitration or other specific clauses. */}
        </div>
      )}


    </div>
  );
};

export default PrivacyAndTerms;
